# Generated by Django 5.1.6 on 2025-03-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0002_remove_user_age_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(default='dog', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(default='Your fav pet', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
